<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 27.04.2018
 * Time: 2:57
 */

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersCitiesSeeder extends Seeder
{
    public function run()
    {
        $data = array(
            array("user_id" => 51, "id" => 1, "city_id" => 98),
            array("user_id" => 95, "id" => 2, "city_id" => 11),
            array("user_id" => 52, "id" => 3, "city_id" => 50),
            array("user_id" => 91, "id" => 4, "city_id" => 6),
            array("user_id" => 86, "id" => 5, "city_id" => 99),
            array("user_id" => 82, "id" => 6, "city_id" => 70),
            array("user_id" => 92, "id" => 7, "city_id" => 73),
            array("user_id" => 5, "id" => 8, "city_id" => 44),
            array("user_id" => 76, "id" => 9, "city_id" => 34),
            array("user_id" => 87, "id" => 10, "city_id" => 34),
            array("user_id" => 19, "id" => 11, "city_id" => 11),
            array("user_id" => 36, "id" => 12, "city_id" => 17),
            array("user_id" => 57, "id" => 13, "city_id" => 34),
            array("user_id" => 53, "id" => 14, "city_id" => 43),
            array("user_id" => 14, "id" => 15, "city_id" => 65),
            array("user_id" => 7, "id" => 16, "city_id" => 47),
            array("user_id" => 26, "id" => 17, "city_id" => 69),
            array("user_id" => 55, "id" => 18, "city_id" => 35),
            array("user_id" => 75, "id" => 19, "city_id" => 72),
            array("user_id" => 73, "id" => 20, "city_id" => 19),
            array("user_id" => 78, "id" => 21, "city_id" => 19),
            array("user_id" => 65, "id" => 22, "city_id" => 17),
            array("user_id" => 33, "id" => 23, "city_id" => 1),
            array("user_id" => 40, "id" => 24, "city_id" => 39),
            array("user_id" => 99, "id" => 25, "city_id" => 17),
            array("user_id" => 81, "id" => 26, "city_id" => 20),
            array("user_id" => 75, "id" => 27, "city_id" => 35),
            array("user_id" => 32, "id" => 28, "city_id" => 91),
            array("user_id" => 88, "id" => 29, "city_id" => 20),
            array("user_id" => 39, "id" => 30, "city_id" => 11),
            array("user_id" => 72, "id" => 31, "city_id" => 88),
            array("user_id" => 66, "id" => 32, "city_id" => 2),
            array("user_id" => 18, "id" => 33, "city_id" => 66),
            array("user_id" => 77, "id" => 34, "city_id" => 93),
            array("user_id" => 44, "id" => 35, "city_id" => 45),
            array("user_id" => 85, "id" => 36, "city_id" => 18),
            array("user_id" => 94, "id" => 37, "city_id" => 1),
            array("user_id" => 93, "id" => 38, "city_id" => 78),
            array("user_id" => 1, "id" => 39, "city_id" => 40),
            array("user_id" => 60, "id" => 40, "city_id" => 15),
            array("user_id" => 60, "id" => 41, "city_id" => 80),
            array("user_id" => 57, "id" => 42, "city_id" => 35),
            array("user_id" => 99, "id" => 43, "city_id" => 99),
            array("user_id" => 48, "id" => 44, "city_id" => 97),
            array("user_id" => 47, "id" => 45, "city_id" => 67),
            array("user_id" => 89, "id" => 46, "city_id" => 78),
            array("user_id" => 91, "id" => 47, "city_id" => 91),
            array("user_id" => 71, "id" => 48, "city_id" => 51),
            array("user_id" => 2, "id" => 49, "city_id" => 20),
            array("user_id" => 100, "id" => 50, "city_id" => 95),
            array("user_id" => 13, "id" => 51, "city_id" => 67),
            array("user_id" => 70, "id" => 52, "city_id" => 22),
            array("user_id" => 22, "id" => 53, "city_id" => 25),
            array("user_id" => 86, "id" => 54, "city_id" => 27),
            array("user_id" => 54, "id" => 55, "city_id" => 36),
            array("user_id" => 62, "id" => 56, "city_id" => 94),
            array("user_id" => 62, "id" => 57, "city_id" => 83),
            array("user_id" => 19, "id" => 58, "city_id" => 96),
            array("user_id" => 95, "id" => 59, "city_id" => 32),
            array("user_id" => 67, "id" => 60, "city_id" => 70),
            array("user_id" => 91, "id" => 61, "city_id" => 62),
            array("user_id" => 59, "id" => 62, "city_id" => 97),
            array("user_id" => 24, "id" => 63, "city_id" => 2),
            array("user_id" => 91, "id" => 64, "city_id" => 81),
            array("user_id" => 4, "id" => 65, "city_id" => 12),
            array("user_id" => 2, "id" => 66, "city_id" => 51),
            array("user_id" => 38, "id" => 67, "city_id" => 24),
            array("user_id" => 67, "id" => 68, "city_id" => 87),
            array("user_id" => 21, "id" => 69, "city_id" => 57),
            array("user_id" => 7, "id" => 70, "city_id" => 22),
            array("user_id" => 74, "id" => 71, "city_id" => 91),
            array("user_id" => 32, "id" => 72, "city_id" => 5),
            array("user_id" => 8, "id" => 73, "city_id" => 87),
            array("user_id" => 92, "id" => 74, "city_id" => 18),
            array("user_id" => 38, "id" => 75, "city_id" => 16),
            array("user_id" => 21, "id" => 76, "city_id" => 99),
            array("user_id" => 4, "id" => 77, "city_id" => 33),
            array("user_id" => 48, "id" => 78, "city_id" => 78),
            array("user_id" => 64, "id" => 79, "city_id" => 96),
            array("user_id" => 65, "id" => 80, "city_id" => 44),
            array("user_id" => 46, "id" => 81, "city_id" => 40),
            array("user_id" => 80, "id" => 82, "city_id" => 76),
            array("user_id" => 29, "id" => 83, "city_id" => 54),
            array("user_id" => 65, "id" => 84, "city_id" => 100),
            array("user_id" => 63, "id" => 85, "city_id" => 19),
            array("user_id" => 53, "id" => 86, "city_id" => 2),
            array("user_id" => 35, "id" => 87, "city_id" => 13),
            array("user_id" => 29, "id" => 88, "city_id" => 61),
            array("user_id" => 82, "id" => 89, "city_id" => 10),
            array("user_id" => 68, "id" => 90, "city_id" => 76),
            array("user_id" => 66, "id" => 91, "city_id" => 74),
            array("user_id" => 29, "id" => 92, "city_id" => 27),
            array("user_id" => 58, "id" => 93, "city_id" => 55),
            array("user_id" => 17, "id" => 94, "city_id" => 79),
            array("user_id" => 43, "id" => 95, "city_id" => 44),
            array("user_id" => 49, "id" => 96, "city_id" => 32),
            array("user_id" => 79, "id" => 97, "city_id" => 20),
            array("user_id" => 59, "id" => 98, "city_id" => 71),
            array("user_id" => 44, "id" => 99, "city_id" => 39),
            array("user_id" => 16, "id" => 100, "city_id" => 47)
        );
        DB::table('users_cities')->insert($data);
    }

}